services:
  db:
    image: postgres:15
    restart: unless-stopped
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: api_ts_db
    volumes:
      - postgres_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"

  api:
    build: .
    depends_on:
      - db
    ports:
      - "3333:3333"
    environment:
      PORT: 3333
      NODE_ENV: development
      JWT_SECRET_KEY: mysupersecret
      APP_URL: http://localhost:3000
      DATABASE_URL: "postgresql://postgres:postgres@db:5432/api_ts_db?schema=public"
    volumes:
      - .:/app
      - /app/node_modules
    command: >
      sh -c "
        npx prisma generate &&
        npx prisma db push &&
        npm run dev
      "

volumes:
  postgres_data:
